Figaro.require_keys(
  "PAYMONGO_PK", "PAYMONGO_SK",
  "CLOUDINARY_CLOUD_NAME", "CLOUDINARY_API_KEY", "CLOUDINARY_SECRET_KEY", "CLOUDINARY_FOLDER_NAME",
  "MAILTRAP_USERNAME", "MAILTRAP_PASSWORD", "MAILTRAP_ADDRESS", "MAILTRAP_DOMAIN", "MAILTRAP_PORT"
)